name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16   # 🔥 FIX (use 16 instead of 18)

    - name: Install Backend
      run: |
        cd Experiment9/server
        npm install

    - name: Install Frontend
      run: |
        cd Experiment9/client
        npm install

    - name: Build Frontend
      run: |
        cd Experiment9/client
        CI=false npm run build